services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${bens_root_password}
      MYSQL_DATABASE: ${bens_db}
      MYSQL_USER: ${bens_user}
      MYSQL_PASSWORD: ${bens_password}
    ports: ["3308:3306"]
    volumes: ["mysql_data:/var/lib/mysql"]
    networks: [demonetwork]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: ${bens_user}
      PMA_PASSWORD: ${bens_password}
    ports: ["8081:80"]
    depends_on: [mysql]
    networks: [demonetwork]

volumes:
  mysql_data:
networks:
  demonetwork: